version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
