org: fcandelam
app: aws-node-culqi
service: aws-node-culqi
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  tokenFunction:
    handler: src/controllers/tokenController.handler
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PORT: ${env:REDIS_PORT}
      POSTGRES_HOST: ${env:POSTGRES_HOST}
      POSTGRES_DB_PORT: ${env:POSTGRES_DB_PORT}
      POSTGRES_USER: ${env:POSTGRES_USER}
      POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${env:POSTGRES_DB_NAME}
    events:
      - httpApi:
          path: /tokens
          method: post
  cardFunction:
    handler: src/controllers/chargeController.handler
    events:
      - httpApi:
          path: /charges
          method: post
    environment:
      REDIS_HOST: ${env:REDIS_HOST}
      REDIS_PORT: ${env:REDIS_PORT}

custom:
  esbuild:
    bundle: true
    minify: false

plugins:
  - serverless-offline
  - serverless-esbuild
